### ISSUE TITLE
Decimal formats

### ISSUE THREAD

**Issue by jesjimher** [akashpjames/sms-import-for-ynab#2]
Hi, I've found that app seems to use a fixed format por decimal separator (I guess it's a single dot). In my country comma is used for decimals, so 106,70 gets correctly imported in YNAB... but as a 10670 amount :-).

Would it be possible to configure decimal and thousands separator in settings, or something like that?

Thanks!

**Comment by akashpjames** [comment]
@jesjimher  Sure, I can make that change. But, I need a little more info.
In India, price in the message comes like this -> 1,000.00 and it should be converted as 1000 and that's what the app does currently. Decimal places are separated by `.` and the `,` is introduced to increase the readability.
So there are two symbols in our system.

I understood that instead of `.` you have `,`. But, which symbol are you using for readability?
Is there any symbol other than `,` in your bank transactions messages?

We can make it dynamic asking the user to input that value. I will try to add the change within 2-3 days based on my free time.

**Comment by jesjimher** [comment]
Here (and in most of Europe) is the opposite: comma for decimals, dot for thousands. So a thousand (1000) would be 1.000,00.

**Comment by akashpjames** [comment]
Got it, thanks. I will push the change tomorrow.

**Comment by akashpjames** [comment]
@jesjimher Fixed and created a new release(0.0.3) to fix this issue.
It will ignore both `,` and `.` from the price now.
https://github.com/akashpjames/sms-import-for-ynab/releases/tag/0.0.3

**Comment by jesjimher** [comment]
Works fine, thanks!
